server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_db
    username: quickbite
    password: quickbite
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.quickbite.payment_service.events.OrderPlacedEvent